create table public.user_logins (
  id bigint generated by default as identity not null,
  logged_in_at timestamp with time zone not null default now(),
  user_id uuid null,
  constraint user_logins_pkey primary key (id),
  constraint user_logins_user_id_fkey foreign KEY (user_id) references profiles (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;